refactor: following demo

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -11,40 +11,28 @@ jobs:
     runs-on: ubuntu-latest
     name: Build Stage
 
-    strategy:
-      matrix:
-        node-version: [16.x]
-
     steps:
+      - name: Checkout
       - uses: actions/checkout@v3
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
         uses: actions/setup-node@v3
         with:
-          node-version: ${{matrix.node-version}}
-          cache: 'yarn'
-          cache-dependency-path: ./yarn.lock
-
-      - name: Run build
-        working-directory: ./
-        run: yarn build
-
-  lint:
-    runs-on: ubuntu-latest
-    name: Build Stage
-
-    strategy:
-      matrix:
-        node-version: [16.x]
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{matrix.node-version}}
-          cache: 'yarn'
-          cache-dependency-path: ./yarn.lock
-
-      - name: Run linter
-        working-directory: ./
-        run: yarn lint
+          node-version: '16'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
